//
//  HomePresenter.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 04/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentData(response: Home.FetchHome.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentData(response: Home.FetchHome.Response)
  {
    let viewModel = Home.FetchHome.ViewModel(evidenza: response.evidenza, vetrinaband: response.vetrinaband, eventi: response.eventi)
    viewController?.displayData(viewModel: viewModel)
  }
}
