//
//  HomeWorker.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 04/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    func fetchHome(lat: Double, lon: Double, completionHandler: @escaping (Home.FetchHome.Response?) -> Void)
    {
        var params: [[String: Any]] = [["name": "lat","value":"\(lat)"],["name": "lon","value":"\(lon)"]]
        
        NetworkManager.shared.restCall(method: "POST", end_point: MyoozikAPIEndpoint.getHome().url()!, params: params, files: []){ (result) -> Void in
            print("result");
            
            do {
                if let json = result as? Data{
                    let decoder = JSONDecoder()
                    let homeModel = try decoder.decode(Home.FetchHome.Response.self, from: json)
                    print(homeModel)
                    
                    completionHandler(homeModel)
                }
                
            } catch let err {
                print("Err", err)
            }
            
        }
    }
}
