//
//  EventoDetailModels.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 24/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EventoDetail
{
  // MARK: Use cases
  
    struct evento: Codable
    {
        var nome: String
        var titolo: String
        var cover: String
        var token: String
        var date_label: String
        var latitudine: Double
        var longitudine: Double
        var descrizione: String
    }
    struct band: Codable
    {
        var nome: String
        var cover: String
        var token: String
    }
    
    enum FetchEventoDetail
        {
            struct Request
            {
            }
            struct Response: Codable
            {
                var evento: evento?
                var band: [band]?
            }
            struct ViewModel
            {
                var evento: evento?
                var band: [band]?
            }
    }
}
