//
//  EventoDetailPresenter.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 24/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventoDetailPresentationLogic
{
  func presentDetail(response: EventoDetail.FetchEventoDetail.Response)
}

class EventoDetailPresenter: EventoDetailPresentationLogic
{
  weak var viewController: EventoDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentDetail(response: EventoDetail.FetchEventoDetail.Response)
  {
    let viewModel = EventoDetail.FetchEventoDetail.ViewModel()
    viewController?.displayDetail(viewModel: viewModel)
  }
}
