//
//  VetrinaRouter.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 26/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VetrinaRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VetrinaDataPassing
{
  var dataStore: VetrinaDataStore? { get }
}

class VetrinaRouter: NSObject, VetrinaRoutingLogic, VetrinaDataPassing
{
  weak var viewController: VetrinaViewController?
  var dataStore: VetrinaDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: VetrinaViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: VetrinaDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
