//
//  VetrinaInteractor.swift
//  Myoozik
//
//  Created by Alessandro Bolattino on 26/04/18.
//  Copyright (c) 2018 Mussini SAS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VetrinaBusinessLogic
{
  func doSomething(request: Vetrina.Something.Request)
}

protocol VetrinaDataStore
{
  //var name: String { get set }
}

class VetrinaInteractor: VetrinaBusinessLogic, VetrinaDataStore
{
  var presenter: VetrinaPresentationLogic?
  var worker: VetrinaWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Vetrina.Something.Request)
  {
    worker = VetrinaWorker()
    worker?.doSomeWork()
    
    let response = Vetrina.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
